services:
  ai-api:
    build: ./backend/ai-api
    ports:
      - "8000:8000"
    volumes:
      - rembg_models:/root/.u2net
    restart: always

  bridge-api:
    build: ./backend/bridge-api
    ports:
      - "5002:5002"
    environment:
      - PYTHON_API_URL=http://ai-api:8000/remove-bg
      - MONGODB_URI=mongodb://mongodb:27017/removebg_saas
      - PUBLIC_URL=https://api.buildora.cloud
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
      - ADMIN_ID=1234
      - ADMIN_PASSWORD=admin789
    depends_on:
      - ai-api
      - mongodb
    restart: always

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: always

volumes:
  mongodb_data:
  rembg_models:
